CREATE USER DEV4_06 IDENTIFIED BY DEV4_06;
GRANT CONNECT, RESOURCE TO DEV4_06;
GRANT ALTER SESSION TO DEV4_06;
CONN DEV4_06/DEV4_06;

CREATE SEQUENCE ID_SEQ START WITH 0 INCREMENT BY 1 MAXVALUE 10000 MINVALUE 0 NOCYCLE;

CREATE TABLE MEMBER(
	ID VARCHAR2(500),
	PASSWORD VARCHAR2(16) NOT NULL,
	EMAIL VARCHAR2(40) NOT NULL UNIQUE,
	NAME VARCHAR2(50) NOT NULL,
	BIRTHDAY VARCHAR2(0) NOT NULL,
	PHONENUMBER VARCHAR2(11) NOT NULL UNIQUE,
	ADDRESS1 VARCHAR2(100) NOT NULL,
	ADDRESS2 VARCHAR2(100) NOT NULL,
	ZIPCODE VARCHAR2(100) NOT NULL,
	MANAGER CHAR(1) DEFAULT 0 NOT NULL,
	REGDATE VARCHAR2(10) NOT NULL,
	PATH VARCHAR2(500) NOT NULL,
	CONSTRAINT MEMBER_PK PRIMARY KEY(ID)
);